# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

codecov:
  notify:
    wait_for_ci: yes
    after_n_builds: 23 # (reusable-test.yml instances in cicd.yml) * (# configurations per instance)
comment:
    after_n_builds: 23 # (reusable-test.yml instances in cicd.yml) * (# configurations per instance)
coverage:
  status:
    project:
      default:
        threshold: 2%
