# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

codecov:
  notify:
    wait_for_ci: yes
    after_n_builds: 28 # (unit_tests, bpf2c) * (Debug, Release)
comment:
    after_n_builds: 28 # (unit_tests, bpf2c) * (Debug, Release)
coverage:
  status:
    project:
      default:
        threshold: 2%
