/*
 *  Copyright (c) Microsoft Corporation
 *  SPDX-License-Identifier: MIT
 */

import "wtypes.idl";

interface ebpf_program_types
{
#include "ebpf_program_types.h"
    typedef ebpf_program_information_t* ebpf_program_information_pointer_t;
}