// Copyright (c) Microsoft Corporation
// SPDX-License-Identifier: MIT

#define EBPF_VERSION_MAJOR 0
#define EBPF_VERSION_MINOR 7
#define EBPF_VERSION_REVISION 0

#define EBPF_VERSION_STRINGIZE(MAJOR, MINOR, REVISION) #MAJOR "." #MINOR "." #REVISION
#define EBPF_VERSION EBPF_VERSION_STRINGIZE(EBPF_VERSION_MAJOR, EBPF_VERSION_MINOR, EBPF_VERSION_REVISION)
