<?xml version="1.0" encoding="utf-8"?>
<!--
  Copyright (c) eBPF for Windows contributors
  SPDX-License-Identifier: MIT
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="NuGet">
    <TargetFramework>native</TargetFramework>
    <_NuGetTargetFallbackMoniker>$(_NuGetTargetFallbackMoniker);native,Version=v0.0</_NuGetTargetFallbackMoniker>
    <RestorePackages>true</RestorePackages>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EverParse"
                      Version="[2022.6.13]"
                      GeneratePathProperty="true"
                      IncludeAssets="none"
                      PrivateAssets="all" />
  </ItemGroup>
</Project>
