# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

name: "bpf2c-test"

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415
      with:
        submodules: 'recursive'

    - name: Install Dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        sudo apt-get update
        sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel nuget
        python3 -m pip install external/parcon
        python3 -m pip install --require-hash -r tests/bpf2c_tests/requirements.txt

    - name: Restore nuget packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        nuget restore

    - name: Fix include folder
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        rm -rf include/asm include/linux

    - name: Build & run tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd tests/bpf2c_tests
        make
        ./bpf2c_tests -s

