# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

name: "bpf2c-test"

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        sudo apt-get update
        sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel nuget
        python3 -m pip install --upgrade "pip<21.0"
        python3 -m pip install -r external/ubpf/requirements.txt

    - name: Restore nuget packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        nuget restore

    - name: Fix include folder
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        rm -rf include/asm include/linux
    
    - name: Build & run tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd tests/bpf2c_tests
        make
        ./bpf2c_tests -s
        
