# Copyright (c) eBPF for Windows contributors
# SPDX-License-Identifier: MIT

# This workflow updates NuGet packages and creates a pull request with the changes.
---
name: nuget_update

on:
  # Allow this workflow to be manually triggered.
  workflow_dispatch:

  # Run this once a week on saturday at 9pm UTC.
  schedule:
    - cron: '0 21 * * 6'

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for PR creation

    runs-on: windows-2025

    steps:
      # Check out the main repo.
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1  # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          # Only check out main repo, not submodules.
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Cache nuget packages
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        env:
          cache-name: cache-nuget-modules
        with:
          path: packages
          key: ${{ runner.os }}-nuget-v2-${{ hashFiles('installer/packages.config') }}

      - name: Restore NuGet packages
        working-directory: ${{ github.workspace }}
        run: nuget restore -noninteractive -verbosity detailed installer\packages.config -PackagesDirectory packages

      # Update nuget packages used by the solution.
      - name: Update NuGet packages
        run: |
          nuget update -noninteractive -verbosity detailed installer\packages.config -RepositoryPath packages

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update NuGet packages
          title: Update NuGet packages
          body: |
            This is an automated pull request by the GitHub Action 'nuget_update'.
            Please review the changes and merge if appropriate.
          labels: |
            automated pr
            nuget update
          branch: nuget_update_${{ hashFiles('installer/packages.config') }}
          base: ${{ github.event.workflow_run.head_branch }}
