# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

name: Run Tests

on:
  workflow_run:
    workflows:
      - MSBuild
    types:
      - completed

jobs:
  run_tests:
    strategy:
      matrix:
        configurations: [Release]
    runs-on: [windows, ebpf_cicd_tests]
    env:
      # Configuration type to build.
      # You can convert this to a build matrix if you need coverage of multiple configuration types.
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

      BUILD_PLATFORM: x64

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Download build artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Required, workflow file name or ID
        workflow: build.yml
        workflow_conclusion: success
        name: Build x64 ${{ matrix.configurations }}
        path: ${{ github.workspace }}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}

    - name: Set up CI/CD Tests
      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
      run: |
        ./setup_ebpf_cicd_tests.ps1

    - name: Execute CI/CD Tests
      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
      run: |
        ./execute_ebpf_cicd_tests.ps1

    - name: Clean up CI/CD Tests
      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
      run: |
        ./cleanup_ebpf_cicd_tests.ps1

    - name: Upload any crash dumps
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Crash-Dumps-${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}
        path: c:/dumps/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
        retention-days: 5