# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# This workflow executes a single test, optionally gathering code coverage and logs.

name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      result_artifact:
        required: true
        type: string

jobs:
  upload_results:
    runs-on: ubuntu-latest
    steps:
    - name: Download performance result artifacts
      uses: actions/download-artifact@v2
      with:
        name: Test-Logs-${{inputs.result_artifact}}
        path: ${{github.workspace}}/results_artifact

    - name: Gather CSV results into results directory
      run: |
        mkdir -p ${{github.workspace}}/results/${{github.sha}}
        curl https://raw.githubusercontent.com/microsoft/bpf_performance/1a50dae54c0c1d8b7f73331936e69a7154b3f659/scripts/gather_csv.sh > gather_csv.sh
        sha256sum gather_csv.sh | grep a279517d50093eaa46778642620ec11b2c07f47ace61c4d854982e23c46f22fa -q || exit 1
        chmod a+x gather_csv.sh
        ./gather_csv.sh ${{github.workspace}}/results_artifact ${{github.workspace}}/results/${{github.sha}}/results

    - name: Post-process results
      run: |
        # Download script to convert CSV to SQL from GitHub.
        curl https://raw.githubusercontent.com/microsoft/bpf_performance/85d6f2f78065d4ecebdfc33ff1afddb4c4241b9e/scripts/process_results.py > process_results.py
        # Compare hash of downloaded script.
        sha256sum process_results.py | grep 313d24cce580ec2ecc79667fab1f7fc577ca0c1e6b88d3585a606bd4ac5f1427 -q || exit 1
        # Run script to convert CSV to SQL.
        python3 ./process_results.py --csv-directory ${{github.workspace}}/results --sql-script-file ${{github.workspace}}/results/upload.sql --commit_id ${{github.sha}} --platform "Windows 2019" --repository ${{github.repository}}

    - name: Upload results to POSTGRES
      env:
        PGHOST: ${{secrets.PGHOST}}
        PGUSER: ${{secrets.PGUSER}}
        PGPORT: ${{secrets.PGPORT}}
        PGDATABASE: ${{secrets.PGDATABASE}}
        PGPASSWORD: ${{secrets.PGPASSWORD}}
      run: |
        psql -f ${{github.workspace}}/results/upload.sql