//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ebpfnetsh.rc
//
#define HLP_EBPF_ADD_PROGRAM 101
#define HLP_EBPF_ADD_PROGRAM_EX 102
#define HLP_EBPF_DELETE_PROGRAM 103
#define HLP_EBPF_DELETE_PROGRAM_EX 104
#define HLP_EBPF_SET_PROGRAM 105
#define HLP_EBPF_SET_PROGRAM_EX 106
#define HLP_EBPF_SHOW_PROGRAMS 107
#define HLP_EBPF_SHOW_PROGRAMS_EX 108
#define HLP_EBPF_SHOW_DISASSEMBLY 109
#define HLP_EBPF_SHOW_DISASSEMBLY_EX 110
#define HLP_EBPF_SHOW_SECTIONS 111
#define HLP_EBPF_SHOW_SECTIONS_EX 112
#define HLP_EBPF_SHOW_VERIFICATION 113
#define HLP_EBPF_SHOW_VERIFICATION_EX 114
#define HLP_EBPF_SHOW_MAPS 115
#define HLP_EBPF_SHOW_MAPS_EX 116
#define HLP_EBPF_SHOW_LINKS 117
#define HLP_EBPF_SHOW_LINKS_EX 118
#define HLP_EBPF_SHOW_PINS 119
#define HLP_EBPF_SHOW_PINS_EX 120
#define HLP_EBPF_SHOW_PROCESSES 121
#define HLP_EBPF_SHOW_PROCESSES_EX 122
#define HLP_EBPF_PIN_MAP 123
#define HLP_EBPF_PIN_MAP_EX 124
#define HLP_EBPF_PIN_PROGRAM 125
#define HLP_EBPF_PIN_PROGRAM_EX 126
#define HLP_EBPF_UNPIN_MAP 127
#define HLP_EBPF_UNPIN_MAP_EX 128
#define HLP_EBPF_UNPIN_PROGRAM 129
#define HLP_EBPF_UNPIN_PROGRAM_EX 130

#define EBPF_FILE_DESCRIPTION "eBPF for Windows Netsh Helper"
#define EBPF_FILE_NAME "ebpfnetsh.dll"

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 131
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
